### ISSUE TITLE
Docker Support: Unsupported Scheme Error

### ISSUE THREAD

**Issue by yarncraft** [jedisct1/rust-nats#21]
**Error:**

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NatsError { repr: WithDescription(InvalidSchemeError, "Unsupported scheme") }', src/libcore/result.rs:999:5

TCP connections should be supported by the library as they are sometimes necessary in order to connect with NATS docker containers.

Source of the problem:
**const URI_SCHEME: &str = "nats"** in the code (line 29 in client.rs)

**Comment by jedisct1** [comment]
Use nats :// -It is using TCP under the hood.

**Comment by yarncraft** [comment]
Alright, thanks!

**Comment by yarncraft** [comment]
I mistook the code shutting down instantaneously when using nats for an error when using nats, is there a reason for immediately closing the program even when it has subscribers listening for messages? I don't see any other errors.
